/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/portfolio_world.glb -t -k -o app/components/models/World.tsx -r /models --shadows 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { ThreeElements } from "@react-three/fiber";
import { useMemo } from "react";
import { useSession } from "../contexts/SessionContext";

type GLTFResult = GLTF & {
  nodes: {
    frame: THREE.Mesh;
    glass_sphere: THREE.Mesh;
    ground: THREE.Mesh;
    Cone002: THREE.Mesh;
    Cone002_1: THREE.Mesh;
  };
  materials: {
    Poliigon_MetalSteelBrushed_7174_2K: THREE.MeshStandardMaterial;
    Material: THREE.MeshPhysicalMaterial;
    ["GroundDirtRocky020_2K"]: THREE.MeshStandardMaterial;
    ["Silver Spaceship metal plate.001"]: THREE.MeshStandardMaterial;
    ["Solar panels.001"]: THREE.MeshStandardMaterial;
  };
};

export function Spaceship(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/portfolio_world.glb",
  ) as unknown as GLTFResult;

  const glassMaterial = useMemo(() => {
    if (!materials.Material) return null;

    const mat = materials.Material.clone();
    mat.transparent = true;
    mat.opacity = 0.3;
    mat.transmission = 0.969;
    mat.ior = 1.45;
    mat.roughness = 0;
    mat.metalness = 0;
    mat.side = THREE.DoubleSide;
    mat.depthWrite = false;
    return mat;
  }, [materials.Material]);

  const { spaceshipRef } = useSession();

  return (
    <group {...props} dispose={null} ref={spaceshipRef} scale={0.07}>
      <mesh
        name="frame"
        castShadow
        receiveShadow
        geometry={nodes.frame.geometry}
        material={materials.Poliigon_MetalSteelBrushed_7174_2K}
      />
      <mesh
        name="glass_sphere"
        castShadow={false}
        geometry={nodes.glass_sphere.geometry}
        material={glassMaterial || materials.Material}
      />
      <mesh
        name="ground"
        castShadow
        receiveShadow
        geometry={nodes.ground.geometry}
        material={materials["GroundDirtRocky020_2K"]}
      />
      <mesh
        name="Cone"
        castShadow
        receiveShadow
        geometry={nodes.Cone002.geometry}
        material={materials["Silver Spaceship metal plate.001"]}
      />
      <mesh
        name="solar"
        castShadow
        receiveShadow
        geometry={nodes.Cone002_1.geometry}
        material={materials["Solar panels.001"]}
      />
    </group>
  );
}

useGLTF.preload("/models/portfolio_world.glb");
