/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/portfolio_world.glb -t -k -o app/components/models/World.tsx --shadows 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { ThreeElements } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    certificates: THREE.Mesh;
    Cone002: THREE.Mesh;
    Cone002_1: THREE.Mesh;
    contact: THREE.Mesh;
    education_experience: THREE.Mesh;
    frame: THREE.Mesh;
    glass_sphere: THREE.Mesh;
    projects: THREE.Mesh;
    skills: THREE.Mesh;
  };
  materials: {
    ["Material.017"]: THREE.MeshStandardMaterial;
    ["Silver Spaceship metal plate.001"]: THREE.MeshStandardMaterial;
    ["Solar panels.001"]: THREE.MeshStandardMaterial;
    ["Material.016"]: THREE.MeshStandardMaterial;
    ["Material.015"]: THREE.MeshStandardMaterial;
    Poliigon_MetalSteelBrushed_7174_2K: THREE.MeshStandardMaterial;
    Material: THREE.MeshPhysicalMaterial;
    ["Material.014"]: THREE.MeshStandardMaterial;
    ["Material.013"]: THREE.MeshStandardMaterial;
  };
};

export function World(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/portfolio_world.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null} position={-1}>
      <mesh
        name="certificates"
        castShadow
        receiveShadow
        geometry={nodes.certificates.geometry}
        material={materials["Material.017"]}
      />
      <mesh
        name="contact"
        castShadow
        receiveShadow
        geometry={nodes.contact.geometry}
        material={materials["Material.016"]}
      />
      <mesh
        name="education_experience"
        castShadow
        receiveShadow
        geometry={nodes.education_experience.geometry}
        material={materials["Material.015"]}
      />
      <mesh
        name="frame"
        castShadow
        receiveShadow
        geometry={nodes.frame.geometry}
        material={materials.Poliigon_MetalSteelBrushed_7174_2K}
      />
      <mesh
        name="glass_sphere"
        castShadow
        receiveShadow
        geometry={nodes.glass_sphere.geometry}
        material={materials.Material}
      />
      <mesh
        name="projects"
        castShadow
        receiveShadow
        geometry={nodes.projects.geometry}
        material={materials["Material.014"]}
      />
      <mesh
        name="skills"
        castShadow
        receiveShadow
        geometry={nodes.skills.geometry}
        material={materials["Material.013"]}
      />
      <mesh
        name="Cone002"
        castShadow
        receiveShadow
        geometry={nodes.Cone002.geometry}
        material={materials["Silver Spaceship metal plate.001"]}
      />
      <mesh
        name="Cone002_1"
        castShadow
        receiveShadow
        geometry={nodes.Cone002_1.geometry}
        material={materials["Solar panels.001"]}
      />
    </group>
  );
}

useGLTF.preload("/models/portfolio_world.glb");
