import * as THREE from "three";
import { GLTF } from "three-stdlib";
import { ActionName } from "../components/contexts/MonishwarContext";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

export type GLTFResult = GLTF & {
  nodes: {
    avaturn_hair_0: THREE.SkinnedMesh;
    avaturn_hair_1: THREE.SkinnedMesh;
    avaturn_look_0: THREE.SkinnedMesh;
    avaturn_shoes_0: THREE.SkinnedMesh;
    Body_Mesh: THREE.SkinnedMesh;
    Eye_Mesh: THREE.SkinnedMesh;
    EyeAO_Mesh: THREE.SkinnedMesh;
    Eyelash_Mesh: THREE.SkinnedMesh;
    Head_Mesh: THREE.SkinnedMesh;
    Teeth_Mesh: THREE.SkinnedMesh;
    Tongue_Mesh: THREE.SkinnedMesh;
    Hips: THREE.Bone;
    Spine: THREE.Bone;
    Spine1: THREE.Bone;
    Spine2: THREE.Bone;
    Neck: THREE.Bone;
    Head: THREE.Bone;
    LeftShoulder: THREE.Bone;
    LeftArm: THREE.Bone;
    LeftForeArm: THREE.Bone;
    LeftHand: THREE.Bone;
    RightShoulder: THREE.Bone;
    RightArm: THREE.Bone;
    RightForeArm: THREE.Bone;
    RightHand: THREE.Bone;
    LeftUpLeg: THREE.Bone;
    LeftLeg: THREE.Bone;
    RightUpLeg: THREE.Bone;
    RightLeg: THREE.Bone;
    LeftFoot: THREE.Bone;
    LeftToeBase: THREE.Bone;
    RightFoot: THREE.Bone;
    RightToeBase: THREE.Bone;
    LeftHandIndex1: THREE.Bone;
    LeftHandIndex2: THREE.Bone;
    LeftHandIndex3: THREE.Bone;
    LeftHandMiddle1: THREE.Bone;
    LeftHandMiddle2: THREE.Bone;
    LeftHandMiddle3: THREE.Bone;
    LeftHandPinky1: THREE.Bone;
    LeftHandPinky2: THREE.Bone;
    LeftHandPinky3: THREE.Bone;
    LeftHandRing1: THREE.Bone;
    LeftHandRing2: THREE.Bone;
    LeftHandRing3: THREE.Bone;
    LeftHandThumb1: THREE.Bone;
    LeftHandThumb2: THREE.Bone;
    LeftHandThumb3: THREE.Bone;
    LeftEye: THREE.Bone;
    RightEye: THREE.Bone;
    RightHandIndex1: THREE.Bone;
    RightHandIndex2: THREE.Bone;
    RightHandIndex3: THREE.Bone;
    RightHandMiddle1: THREE.Bone;
    RightHandMiddle2: THREE.Bone;
    RightHandMiddle3: THREE.Bone;
    RightHandPinky1: THREE.Bone;
    RightHandPinky2: THREE.Bone;
    RightHandPinky3: THREE.Bone;
    RightHandRing1: THREE.Bone;
    RightHandRing2: THREE.Bone;
    RightHandRing3: THREE.Bone;
    RightHandThumb1: THREE.Bone;
    RightHandThumb2: THREE.Bone;
    RightHandThumb3: THREE.Bone;
  };
  materials: {
    avaturn_hair_0_material: THREE.MeshStandardMaterial;
    avaturn_hair_1_material: THREE.MeshStandardMaterial;
    avaturn_look_0_material: THREE.MeshStandardMaterial;
    avaturn_shoes_0_material: THREE.MeshStandardMaterial;
    Body: THREE.MeshStandardMaterial;
    Eyes: THREE.MeshStandardMaterial;
    EyeAO: THREE.MeshStandardMaterial;
    Eyelash: THREE.MeshStandardMaterial;
    Head: THREE.MeshStandardMaterial;
    Teeth: THREE.MeshStandardMaterial;
    ["Teeth.001"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};
